### ISSUE TITLE
windows下路径错误

### ISSUE THREAD

**Issue by luvsagiri** [hujinbo23/dst-admin-go#1]
配置：cluster=cluster2
报错：
File reading error:  open C:\Users\Administrator/.klei/DoNotStarveTogether/cluster2/cluster_token.txt: The system cannot find the path specified.
2023/05/12 12:14:22 errorHandle.go:15: panic: read cluster_token.txt file error: open C:\Users\Administrator/.klei/DoNotStarveTogether/cluster2/cluster_token.txt: The system cannot find the path specified.
生成新游戏时报错：
open C:\Users\Administrator/.klei/DoNotStarveTogether/cluster3/Caves/server.ini: The system cannot find the path specified.
2023/05/12 12:27:18 gameConfigService.go:348: 生成master_leveldataoverride.txt 文件  C:\Users\Administrator/.klei/DoNotStarveTogether/cluster3/Master/leveldataoverride.lua
open C:\Users\Administrator/.klei/DoNotStarveTogether/cluster3/Master/leveldataoverride.lua: The system cannot find the path specified.
2023/05/12 12:27:18 gameConfigService.go:358: 生成caves_leveldataoverride.lua 文件  C:\Users\Administrator/.klei/DoNotStarveTogether/cluster3/Caves/leveldataoverride.lua
open C:\Users\Administrator/.klei/DoNotStarveTogether/cluster3/Caves/leveldataoverride.lua: The system cannot find the path specified.
2023/05/12 12:27:18 gameConfigService.go:368: 生成master_modoverrides.lua 文件  C:\Users\Administrator/.klei/DoNotStarveTogether/cluster3/Master/modoverrides.lua
2023/05/12 12:27:18 gameConfigService.go:369: 生成caves_modoverrides.lua 文件  C:\Users\Administrator/.klei/DoNotStarveTogether/cluster3/Caves/modoverrides.lua
open C:\Users\Administrator/.klei/DoNotStarveTogether/cluster3/Master/modoverrides.lua: The system cannot find the path specified.
open C:\Users\Administrator/.klei/DoNotStarveTogether/cluster3/Caves/modoverrides.lua: The system cannot find the path specified.
2023/05/12 12:27:18 shellService.go:381: error: exit status 255
2023/05/12 12:27:18 shellService.go:388: shell exec: ps -ef | grep -v grep |grep 'Caves' |sed -n '1P'|awk '{print $2}'
Output:
'ps' is not recognized as an internal or external command,
operable program or batch file.

**Comment by hujinbo23** [comment]
不支持window，window环境请参考[dst-admin-windows](https://github.com/hujinbo23/dst-admin-windows)这个项目

**Comment by luvsagiri** [comment]
> 配置：cluster=cluster2 报错： File reading error: open C:\Users\Administrator/.klei/DoNotStarveTogether/cluster2/cluster_token.txt: The system cannot find the path specified. 2023/05/12 12:14:22 errorHandle.go:15: panic: read cluster_token.txt file error: open C:\Users\Administrator/.klei/DoNotStarveTogether/cluster2/cluster_token.txt: The system cannot find the path specified.



> 不支持window，window环境请参考[dst-admin-windows](https://github.com/hujinbo23/dst-admin-windows)这个项目

好的，谢谢

**Comment by luvsagiri** [comment]
> 不支持window，window环境请参考[dst-admin-windows](https://github.com/hujinbo23/dst-admin-windows)这个项目

你好，我把系统重置成了linux，但是模组设置里的保存配置和更新配置都没有效果，请问该怎么解决呢

**Comment by hujinbo23** [comment]
> > 不支持window，window环境请参考[dst-admin-windows](https://github.com/hujinbo23/dst-admin-windows)这个项目
> 
> 你好，我把系统重置成了linux，但是模组设置里的保存配置和更新配置都没有效果，请问该怎么解决呢 2023/05/12 22:51:42 /home/ubuntu/program/dst-admin-go/api/modApi.go:66 [0.675ms] [rows:28] SELECT * FROM `mod_infos` WHERE `mod_infos`.`deleted_at` IS NULL

请保证 mod_download_path 有配置(dst_config 文件)，并且该路径以及dst-admin-go 目录有读写的权限

**Comment by luvsagiri** [comment]
> > > 不支持window，window环境请参考[dst-admin-windows](https://github.com/hujinbo23/dst-admin-windows)这个项目
> > 
> > 
> > 你好，我把系统重置成了linux，但是模组设置里的保存配置和更新配置都没有效果，请问该怎么解决呢 2023/05/12 22:51:42 /home/ubuntu/program/dst-admin-go/api/modApi.go:66 [0.675ms] [rows:28] SELECT * FROM `mod_infos` WHERE `mod_infos`.`deleted_at` IS NULL
> 
> 请保证 mod_download_path 有配置(dst_config 文件)，并且该路径以及dst-admin-go 目录有读写的权限

我懂了，原来mod配置里的不是现在房间的实时配置只是mod的默认配置呀，请问可以出一个保存上次设置的配置的吗，每次重新配置的话有一点繁琐

**Comment by luvsagiri** [comment]
> 这个功能其实就是mod配置逆向，现在只做了世界配置逆向。这个我记下了

大佬辛苦了，加油
