### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by MuMuloveU** [hujinbo23/dst-admin-go#25]
docker镜像启动之后，访问vps8082端口无信息，测试搭建其他docker无问题，请检查下docker镜像谢谢！

**Comment by hujinbo23** [comment]
请检查下vps 防火墙以及端口映射。第一次运行时，会自动安装安装steamcmd和饥荒专用服务器，会比较慢。自己使用docker logs 查看日志

**Comment by MuMuloveU** [comment]
感谢您的回复，我开放了所有端口的访问权限，且并没有更改端口映射，或许是我太着急了，在我启动镜像之后，大概五分钟，我访问vps的8082端口没有任何回复，并没有网页加载，就反馈了这个lssues，或许我应该多等一会，再次感谢您的回复。
