### ISSUE TITLE
订阅模组搜索不到模组

### ISSUE THREAD

**Issue by 1234-star** [hujinbo23/dst-admin-go#3]
![image](https://github.com/hujinbo23/dst-admin-go/assets/59988945/9e7a5eb7-c7d9-48df-8983-c78be7f5549e)
很多模组都无法搜到

**Comment by 1234-star** [comment]
用模组id还是名字都不行

**Comment by hujinbo23** [comment]
模组查询已经修复了，同时增加了模组id查找，请下载最新的 **release** 版本
