### ISSUE TITLE
[Bug]无法识别宕机还是手动关闭

### ISSUE THREAD

**Issue by baichachaa** [hujinbo23/dst-admin-go#50]
你好，系统没有识别用户手动关闭/开启操作

例如我开启地上/地下宕机检测后，我手动关闭地上/地下

依照我的逻辑，应该是cron检测任务停止了，不在需要检测对应的世界是否宕机了。

但貌似没有这个功能，仍会自动世界。

这还会有另外的问题，游戏没更新完，就启动世界了。

问题版本：1.2.5

**Comment by hujinbo23** [comment]
1.2.7 修复了，如果手动关闭了就不会启动了
